### ISSUE TITLE
Special representation for DiagonalMatrix

### ISSUE THREAD

**Issue by aslesarenko** [scalan/scalan#101]
Implement `AbstractMatrix` interface using special optimized representation when the matrix has only diagonal non-zero elements.

**Comment by Maksim-Zhuravlev** [comment]
I am going to implement that this weekend.

**Comment by Maksim-Zhuravlev** [comment]
Please review the pull request.
I need several advices on following steps:
- Testing
- Usage of IF THEN ELSE - I did not manage to compile the code with this construction, so used Scala's if.
- I also did not manage to find example of check for matrix sizes matching. And, thus, did not neither describe several special cases nor report errors. Are sizes checked at engine level in some tricky way or the check is missing for now?

**Comment by aslesarenko** [comment]
@Maksim-Zhuravlev looks good.
1) Please add integration tests in 'LmsMvmItTests'
2) look at `readme` file, it is explicitly mentioned there
3) no checks right now. In Scalan all the code can be evaluated in Seq context (see traits with Seq suffix). Added new issue #124

**Comment by alexeyr** [comment]
> Usage of IF THEN ELSE - I did not manage to compile the code with this construction, so used Scala's if.

Note that you need `===` instead of `==`, as mentioned in the readme (unfortunately, a known pitfall).

**Comment by Maksim-Zhuravlev** [comment]
Please review new version.
I've added tests and fixed several issues highlighted by them.
Thanks for clarification on IF THEN ELSE.
