### ISSUE TITLE
Special representation for ConstMatrix

### ISSUE THREAD

**Issue by aslesarenko** [scalan/scalan#102]
Implement AbstractMatrix interface using special optimized representation when the matrix has the same value in all elements.
For example, to represent the matrix below we can use `(Int, (Int,Double))` type to keep in memory only `numColumns`, `numRows`, and the value. This can be acheived by declaring the properties we want to store in memory as parameters of the class constructor with `val` modifier.

3 3 3
3 3 3
3 3 3
3 3 3

**Comment by maleficxp** [comment]
Do I understand correctly than it must be a new abstract class in `trait Matrices` from `Matrices.scala`?

**Comment by aslesarenko** [comment]
Yes, and you also need to use `BoilerplateTool` to regenerate boilerplate in `MatricesImpl.scala`

**Comment by maleficxp** [comment]
I have some problem with this case. If I try to add additional parameter to constructor `val item: Rep[T]` boilerplate shows me the following:
`WARNING: cannot generate converter from AbstractMatrix to ConstantMatrix: missing fields List(item)`
AbstractMatrix doesn't have `item` field, but ConstantMatrix does. What is the right way to solve this problem?

**Comment by aslesarenko** [comment]
This problem is unsolvable. :)
Not every pair of representations are mutually convertible because they may contain not equivalent amount of information. They are not necessary isomorphic. This warning is just telling about each such case.

**Comment by aslesarenko** [comment]
See [this test](https://github.com/scalan/scalan/blob/master/lms-backend/src/it/scala/scalan/it/lms/LmsLinAlgItTests.scala#L30-30) for an example how to run generic `mvm` with specific representation.

**Comment by maleficxp** [comment]
I created a pull request with ConstMatrix implementation, can you check it out?
