### ISSUE TITLE
Fix deserialization issue correctly

### ISSUE THREAD

**Issue by alexeyr** [scalan/scalan#105]
See the discussion at https://github.com/scalan/scalan/pull/62/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceL55 and http://www.scala-sbt.org/0.13/docs/Running-Project-Code.html:

> the deserialization code ensures that the right class loader is used, as in https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/util/ClassLoaderObjectInputStream.scala or https://github.com/scala/scala/blob/2.11.x/src/actors/scala/actors/remote/JavaSerializer.scala#L20

**Comment by alexeyr** [comment]
I'll do it myself, I am currently waiting for a reply to a question anyway.

**Comment by 4e6** [comment]
You're our savior :+1:
