### ISSUE TITLE
Update LMS

### ISSUE THREAD

**Issue by alexeyr** [scalan/scalan#119]
LMS now has a non-snapshot version released (http://search.maven.org/#artifactdetails|org.scala-lang.lms|lms-core_2.11|0.9.0|). We should merge it (or 1.0.0-SNAPSHOT) into our fork. @aslesarenko please assign to someone.

**Comment by alexeyr** [comment]
Preferably should be done after the dependent projects are updated to current Scalan state, which is why I don't just do this immediately.

**Comment by aslesarenko** [comment]
It should be done together with #122. Otherwise it doesn't make much sense.

**Comment by alexeyr** [comment]
Done in #167 (to our fork since pull requests aren't accepted yet).
