### ISSUE TITLE
Consider using ReflectMethod instead of ReflectField

### ISSUE THREAD

**Issue by aslesarenko** [scalan/scalan#149]
ReflectField.get may return value from the base class. This may lead to unexpected behaviour and tricky to catch.

Quote from docs.
"If symbol represents a field of a base class with respect to the class of the receiver, and this base field is overriden in the class of the receiver, then this method will retrieve the value of the base field. To achieve overriding behavior, use reflectMethod on an accessor."

````
  private[this] def extractParamsByReflection(d: Any, fieldMirrors: List[FieldMirror]): List[Any] =
    fieldMirrors.map(_.bind(d).get)
````

**Comment by alexeyr** [comment]
The current method also works with private fields, e.g. those created when writing `[A: Elem]`. On the other hand, it may be a good idea to disallow this for consistency now anyway.
