### ISSUE TITLE
Implement wrappers of classes from scala.collection.immutable

### ISSUE THREAD

**Issue by aslesarenko** [scalan/scalan#20]

**Comment by ivan-zapreev** [comment]
I'd like to work on this one, if of course one could make the bug description somewhat more vivid :) 
Which classes need to be wrapped?
What kind of wrappers are needed?
Where should this wrappers be put to use and how?
How is it possible to test the changes?

**Comment by aslesarenko** [comment]
This is closely related with #21. After the wrappers are declared all the tests can be generated based on declaration. 
See scalan.util.Exceptions, scalan.collection.HashSet for an example of  wrapper declarations.

**Comment by ivan-zapreev** [comment]
Ok, I will start working on this one then as well, I will keep you posted :)

**Comment by aslesarenko** [comment]
All wrappers will be generated by [Scalanizer](https://github.com/scalan/scalanizer) automatically.
