### ISSUE TITLE
Generate *Dsl/*DslSeq/*DslExp automatically if they aren't present

### ISSUE THREAD

**Issue by alexeyr** [scalan/scalan#25]
Currently we still need a bit of boilerplate in the file defining domain type. In particular see

    trait PointsDsl extends impl.PointsAbs
    trait PointsDslSeq extends impl.PointsSeq
    trait PointsDslExp extends impl.PointsExp

in README. These should be generated automatically. However, in some cases we have things defined in these traits. They should be either moved elsewhere or generation should only be done if these traits don't exist already.

**Comment by aslesarenko** [comment]
To move these traits somewere would be incovenient. Let's add more smartness into Scalan-meta.

**Comment by alexeyr** [comment]
I don't mean moving these traits, but members defined in them. E.g. define `trait PointsDslExtensionSeq extends PointsDslSeq {...}` in this case. 

> And if they are generated they should reside in corresponding Impl file.

Yes, of course.
