### ISSUE TITLE
Review `createDefinition` use in `mirrorLambda` and `mirrorThunk`

### ISSUE THREAD

**Issue by alexeyr** [scalan/scalan#250]
In https://github.com/scalan/scalan/blob/b08d8cc299c498646950a929aaaa3affb7c5579f/core/src/main/scala/scalan/staged/TransformingExp.scala#L226 `createDefinition` is called and this prevents unification with existing alpha-equivalent lambda.

**Comment by aslesarenko** [comment]
Could you propose a PR?

**Comment by alexeyr** [comment]
Simply removing the calls fails "Metadata can be changed by mirror" test. Need to think more about this.
