### ISSUE TITLE
Update scalan-starter to the current version and mention in the readme

### ISSUE THREAD

**Issue by alexeyr** [scalan/scalan#56]
Prerequisite: release a non-snapshot version for Scala 2.11

**Comment by aslesarenko** [comment]
This make sense after #78 is done and released

**Comment by alexeyr** [comment]
I've released version 0.2.10 for now before leaving for ICFP. I think this makes sense to do now, so we can just point people there (and changes in #78 and related shouldn't actually affect scalan-starter much; its tests, perhaps).

**Comment by aslesarenko** [comment]
@alexeyr close?
