### ISSUE TITLE
Separate backend from the main Scalan cake

### ISSUE THREAD

**Issue by alexeyr** [scalan/scalan#78]
We need to split backend/compiler into a separate cake which only refers to Scalan. This will allow reusing the same graph IR in multiple backends, simplify testing and decrease rebuild times.

**Comment by alexeyr** [comment]
First part is done (commits fdc00b1b5fcac230f0d8f3f70b9d8a621e7b5f56 to f6def8512e50b79b9b87d4679286883f3bce1361)

**Comment by alexeyr** [comment]
But programs are still mixed into the Scalan cake, so the same compiler can't be used with multiple _independently created_ programs.

**Comment by aslesarenko** [comment]
@alexeyr this can be closed?

**Comment by alexeyr** [comment]
Yes, this can be closed.
